version : '3.8'
services:
#  cool-nacos:
#    container_name: cool-nacos
#    image: nacos/nacos-server
#    build:
#      context: docker/nacos
#    environment:
#      - MODE=standalone
#    volumes:
#      - ./docker/nacos/logs/:/home/nacos/logs
#      - ./docker/nacos/conf/application.properties:/home/nacos/conf/application.properties
#    ports:
#      - "8848:8848"
#      - "9848:9848"
#      - "9849:9849"
#    depends_on:
#      - cool-mysql
#    links:
#      - cool-mysql
#  cool-mysql:
#    container_name: cool-mysql
#    image: mysql:8.0.26
#    build:
#      context: sql
#      dockerfile: Dockerfile
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./docker/mysql/conf:/etc/mysql/conf.d
#      - ./docker/mysql/logs:/logs
#      - ./docker/mysql/data:/var/lib/mysql
#    command: [
#          'mysqld',
#          '--innodb-buffer-pool-size=80M',
#          '--character-set-server=utf8mb4',
#          '--collation-server=utf8mb4_unicode_ci',
#          '--default-time-zone=+8:00',
#          '--lower-case-table-names=1'
#        ]
#    environment:
#      MYSQL_DATABASE: 'cool-cloud'
#      MYSQL_ROOT_PASSWORD: password
#  cool-redis:
#    container_name: cool-redis
#    image: redis
#    build:
#      context: docker/redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./docker/redis/conf/redis.conf:/home/springcool/redis/redis.conf
#      - ./docker/redis/data:/data
#    command: redis-server /home/springcool/redis/redis.conf
  cool-gateway:
    container_name: cool-gateway
    build:
      context: cool-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#    links:
#      - cool-nacos
#      - cool-redis
  cool-auth:
    container_name: cool-auth
    build:
      context: cool-auth
      dockerfile: ./Dockerfile
    ports:
      - "9200:9200"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#    links:
#      - cool-nacos
#      - cool-redis
  cool-modules-tenant:
    container_name: cool-modules-tenant
    build:
      context: cool-modules/cool-tenant
      dockerfile: ./Dockerfile
    ports:
      - "9700:9700"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
#    links:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
  cool-modules-system:
    container_name: cool-modules-system
    build:
      context: cool-modules/cool-system
      dockerfile: ./Dockerfile
    ports:
      - "9600:9600"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
#    links:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
  cool-modules-gen:
    container_name: cool-modules-gen
    build:
      context: cool-modules/cool-gen
      dockerfile: ./Dockerfile
    ports:
      - "9400:9400"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
#    links:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
  cool-modules-job:
    container_name: cool-modules-job
    build:
      context: cool-modules/cool-job
      dockerfile: ./Dockerfile
    ports:
      - "9500:9500"
#    depends_on:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
#    links:
#      - cool-nacos
#      - cool-redis
#      - cool-mysql
  cool-modules-file:
    container_name: cool-modules-file
    build:
      context: cool-modules/cool-file
      dockerfile: ./Dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./springcool/uploadPath:/home/springcool/uploadPath
  cool-visual-monitor:
    container_name: cool-visual-monitor
    build:
      context: cool-visual/cool-monitor
      dockerfile: ./Dockerfile
    ports:
      - "9100:9100"